new_relic:
  key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>

attr_encrypted:
  key: <%= ENV['ATTR_ENCRYPTED_KEY'] %>

google_maps_embed:
  key: <%= ENV['GOOGLE_MAPS_EMBED_API_KEY'] %>

google_geocode:
  key: <%= ENV['GOOGLE_GEOCODE_API_KEY'] %>

google_analytics:
  key: <%= ENV['GOOGLE_ANALYTICS_API_KEY'] %>

smtp_config:
  user_name: <%= ENV['SMTP_USER_NAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
  address: <%= ENV['SMTP_ADDRESS'] %>
  domain: <%= ENV['SMTP_DOMAIN'] %>
  port: <%= ENV['SMTP_PORT'].to_i %>
  authentication: <%= ENV['SMTP_AUTH'] %>

default_url:
  host: <%= ENV['URL_HOST'] %>
  port: <%= ENV['URL_PORT'].to_i %>

cdn:
  host: <%= ENV['CDN_HOST'] %>

cors:
  origins: <%= ENV.fetch('CORS_ORIGINS', '').split(',') %>

rack_timeout:
  seconds: <%= ENV.fetch('TIMEOUT', 5).to_i %>

donations:
  address: <%= ENV['DONATION_ADDRESS'] %>
  qr_code: <%= ENV['DONATION_QR_CODE'] %>

admin:
  email: <%= ENV.fetch('ADMIN_EMAIL', 'brett@dashous.com') %>

git:
  revision: <%= ENV.fetch('REVISION', `git log --pretty=format:'%h' -n 1`) %>
  github_url: https://github.com/brettclanton001/Dashous

heap_analytics:
  id: <%= ENV['HEAP_ANALYTICS_ID'] %>
